name: Auto Create Pull Requests

on:
  push:
    branches:
      - main

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch all remote branches
        run: |
          git fetch --all

      - name: Get all r/* branches
        id: get_branches
        run: |
          BRANCHES=$(git branch -r | grep 'origin/r/' | sed 's/origin\///')
          echo "r/* branches: $BRANCHES"
          echo "$BRANCHES" > branches.txt

      - name: Create Pull Requests to each r/* branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Set GH_TOKEN for authentication
        run: |
          # Ensure we're on the main branch (the branch that triggered the workflow)
          git checkout main
          git pull origin main

          while IFS= read -r branch; do
            echo "Creating PR for branch: $branch"

            # Ensure the r/* branch exists locally and is up to date
            git fetch origin $branch || echo "Branch $branch not found, skipping."

            # Checkout the r/* branch
            git checkout $branch
            git pull origin $branch

            # Check for changes between the main branch and r/* branch before creating a PR
            if git diff --quiet main..$branch; then
              echo "No changes between main and $branch. Skipping PR creation."
            else
              # Create a pull request from main to r/*
              gh pr create --base "$branch" --head "main" --title "Auto PR: Sync $branch with main" --body "This PR was automatically created by GitHub Actions."
            fi
          done < branches.txt
