name: Auto Create Pull Requests

on:
  push:
    branches:
      - feature/*

jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch all remote branches
        run: |
          git fetch --all

      - name: Get all r/* branches
        id: get_branches
        run: |
          BRANCHES=$(git branch -r | grep 'origin/r/' | sed 's/origin\///')
          echo "r/* branches: $BRANCHES"
          echo "$BRANCHES" > branches.txt

      - name: Create Pull Requests to each r/* branch
        run: |
          while IFS= read -r branch; do
            echo "Creating PR for branch: $branch"
            # Create a pull request for the current branch (r/*)
            gh pr create --base "$branch" --head "${GITHUB_REF##*/}" --title "Auto PR: $branch" --body "This PR was automatically created by GitHub Actions."
          done < branches.txt
