name: Create Pull Request on Merge to Main

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the base branch (r/* branch) and branch to merge (main)
        id: branches
        run: |
          # Extract the base branch (r/* branch)
          BASE_BRANCH=$(git branch -r --list 'origin/r/*' | head -n 1 | sed 's/origin\///')
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

          # The branch to merge is always `main` for this setup
          BRANCH_TO_MERGE="main"
          echo "BRANCH_TO_MERGE=$BRANCH_TO_MERGE" >> $GITHUB_ENV

      - name: Create pull request
        run: gh pr create -B ${{ env.BASE_BRANCH }} -H ${{ env.BRANCH_TO_MERGE }} --title 'Merge ${{ env.BRANCH_TO_MERGE }} into ${{ env.BASE_BRANCH }}' --body 'Created by GitHub action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
