name: Create Pull Requests to r/* Branches

on:
  push:
    branches:
      - main

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate with GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Get all r/* branches
        run: |
          BRANCHES=$(git branch -r | grep 'origin/r/' | sed 's/origin\///')
          echo "Branches: $BRANCHES"
          echo "$BRANCHES" > branches.txt

      - name: Create pull requests to each r/* branch
        run: |
          while IFS= read -r branch; do
            # Create a pull request from main to the r/* branch
            gh pr create --base "$branch" --head "main" --title "Sync with main" --body "Automated PR to sync changes with main branch."
          done < branches.txt
